### ISSUE TITLE
protoc-gen-grpc-federation no longer works without options in v0.12.0

### ISSUE THREAD

**Issue by pkwarren** [mercari/grpc-federation#102]
**Describe the bug**
When protoc-gen-grpc-federation is executed in v0.12.0 without options, it fails with the error:
```
$ buf generate
2024/02/08 14:08:34 grpc-federation: unexpected option format: 
Failure: plugin mercari-grpc-federation: exit status 1
```

This worked in previous versions of the plugin and was relied on by upstream unit tests in github.com/bufbuild/plugins.

** Related Components **
- [x] protoc-gen-grpc-federation
- [ ] grpc-federation-linter
- [ ] grpc-federation-language-server
- [ ] grpc-federation-generator
- [ ] others

**To Reproduce**
Run the `protoc-gen-grpc-federation` plugin with a `buf.gen.yaml` file with no `opt:` settings for the plugin.

**Expected behavior**
The plugin should complete without errors (unless options are required now, in case we'll need to tweak how this plugin is invoked for testing.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by goccy** [comment]
Thank you for your report ! This bug has been fixed in [v0.12.1](https://github.com/mercari/grpc-federation/releases/tag/v0.12.1)
