### ISSUE TITLE
Buf dropped alpha support to Wasm plugins

### ISSUE THREAD

**Issue by evacchi** [mercari/grpc-federation#127]
**Describe the bug**

PR https://github.com/bufbuild/buf/pull/2789 dropped support to buf Wasm plugins, so this is a warning that, when you will upgrade this component, you might need some extra work to remove the related code. For instance `_examples/16_code_gen_plugin` will likely need to be deleted

**Related Components**
- [x] protoc-gen-grpc-federation

**Comment by goccy** [comment]
We don't use Buf's wasm plugin so this is not relevant.
