### ISSUE TITLE
Oneof is Reporting Compilation Errors though Using Examples

### ISSUE THREAD

**Issue by hywu-mer** [mercari/grpc-federation#36]
**Describe the bug**

Compiler still requires to specify `grpc.federation.field` even if specified in `oneof` fields.

**Related Components**
- [x] protoc-gen-grpc-federation
- [ ] grpc-federation-linter
- [ ] grpc-federation-language-server
- [ ] others

**To Reproduce**
Steps to reproduce the behavior.

```shell
grpc-federation % cd _examples/10_oneof/proto
proto % protoc -I../proto_deps -I. --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative --grpc-federation_out=. --grpc-federation_opt=paths=source_relative federation/federation.proto

2023/10/20 18:48:05 grpc-federation: value must be specified: value must be specified: ERROR: <input>:1:4: undefined field 'user'
 | sel.user
 | ...^: "user_a" field in "org.federation.UserSelection" message needs to specify "grpc.federation.field" option: "user_b" field in "org.federation.UserSelection" message needs to specify "grpc.federation.field" option
--grpc-federation_out: protoc-gen-grpc-federation: Plugin failed with status code 1.
```

(snippet from the example)
```proto
oneof user {
    User user_a = 1 [
      (grpc.federation.field).oneof = {
        expr: "m.value != $.value"
        messages {
          name: "ua"
          message: "User"
          args: { name: "user_id", string: "a" }
        }
        by: "ua"
      }
    ];
}
```

**Expected behavior**

Successful compilation without errors.

**Additional context**

I am trying to utilize `grpc.federation.field.oneof` to achieve conditional message calls based on the previous message call response. Described in Golang:

```go
firstResponse := client.CallA()
switch firstResponse.GetRes() {
case "SUCCESS":
  secondResponse := client.CallB()
case "FAILED":
  // do nothing
}
```

I am not sure if using `oneof` is the correct way, but the `expr` in `FieldOneof` rule is the only place that I can find for condition judgements. Or is the current version does not support complicated logic?

Looking forward to your responses!

**Comment by goccy** [comment]
@hywu-mer  Hi, Thank you for reporting.
First, `protoc-gen-grpc-federation` may not be up-to-date. Please run `make build` once to make sure you are using the latest version. Second, to access the name of `oneof`, all fields in `oneof` must be of the same type. Please check this as well.

**Comment by hywu-mer** [comment]
@goccy Hello, thank you for your reply!

I did try `make build` and built every necessary tool to folder `bin` in the repository folder. And then I did

```
cd ./_examples/10_oneof
./../../bin/buf generate
```

Still I got the error the same as in the issue :(

Moreover, I am using the examples provided in the `_examples` folder and made no changes to them, so all fields should have `oneof` correctly, I think there must be something set up wrongly at my side or the generator version is not correct? I am not sure...

Looking forward to your response!

**Comment by goccy** [comment]
@hywu-mer 

The command to execute in example is incorrect.

The correct command is the following.

```console
cd _examples/10_oneof
make generate
go test ./
```

**Comment by hywu-mer** [comment]
@goccy 

I think fundamentally, the commands are the same.

After I deleted the generated files in the `_examples/10_oneof` folder, the `make generate` worked for me. 

However, when I tried with the `protoc` command and another `buf` command installed by `homebrew`, I still got the error exactly as in the issue description. Any ideas? 🙇 

In addition, in a `oneof` proto field, do I need at least two inside the `oneof` block, or does only one work?

**Comment by goccy** [comment]
@hywu-mer 

All tools to run example are managed with fixed versions, so you need to use the ones installed in the repository using Makefile.

The case with only one field inside oneof block has not yet been tested, but it is not the intended use.

**Comment by hywu-mer** [comment]
@goccy 

Thank you for answering the question!

Just for the background, because `oneof` is the only place I can find where condition expression `expr` is allowed, I am trying to use `oneof` to achieve conditional calls.

As of now, my understanding is that all dependency messages defined in a `grpc.federation.message.messages` or `grpc.federation.message.resolver` will be called (request to dependency services). But there is a use case for us where we need to determine whether the second call should be made based on the first call result, i.e. `if firstCall.result == sucessful then secondCall()`

May I ask if there is a plan to support this? 🙇

**Comment by goccy** [comment]
For example, by writing a proto like the following, you can write a branch that calls `GetSecondResource` if the result of `GetFirstResource` is `XX` .

```proto

message First {
  resolver {
    method: "GetFirstResource"
    response { name: "res" }
  }
  messages { message: "Condition", args { name: "first", by: "res" } }
}

message Condition {
  oneof cond {
    bool called = 1 [(grpc.federation.field).oneof = {
      expr: "condition for getting Second"
      messages { message: "Second", args { name: "value", by: "$.first.value" }
      by: "true"
    }];

    bool not_called = 2 [(grpc.federation.field).oneof = {
      default: true
      by: "true"
    }];
  }
}

message Second {
  resolver {
    method: "GetSecondResource"
    request { field: "xxx", by: "$.value" } // use first resource value
  }
}

```

**Comment by hywu-mer** [comment]
@goccy Thank you for the detailed explanation! I will try on my side 🙇
