### ISSUE TITLE
Add automated CI job to push protos to BSR

### ISSUE THREAD

**Issue by mfridman** [mercari/grpc-federation#98]
It appears https://github.com/mercari/grpc-federation/commit/baca78bf2421322c97e6977a06931fed29e4058a updated the proto extension numbers, however, this is not yet reflected in https://buf.build/mercari/grpc-federation

Suggestion, add a [push action](https://github.com/bufbuild/buf-push-action) or script to update this anytime proto changes land on main.

**Comment by goccy** [comment]
Thank you for your reports ! We'll try it !
